name: Build test
on:
  - push
  - pull_request
jobs:
  # ubuntu-build-test:
  #   name: Build project (Ubuntu)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Install build dependencies
  #       run: |
  #         sudo apt update
  #         sudo apt install -y build-essential pkg-config \
  #           libncurses5-dev libncursesw5-dev libmpv-dev mpv libnotify4
  #     - name: Compile project
  #       run: |
  #         sudo make install

  macos-build-test:
    name: Build project (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup MacPorts
        uses: melusina-org/setup-macports@v1.1.2
      - name: Install build dependencies
        run: |
          brew install gcc
          sudo port install ncurses
          sudo port install mpv +libmpv
      - name: Compile project
        run: |
          sudo make install
